### motos-api
GET http://localhost:1221/motos

### por id
GET http://localhost:1221/motos/cba9a49d-73b3-11ee-8f01-900f0c2fe266

### por marca
GET http://localhost:1221/motos?brand=kawasaki

### por ciudad
GET http://localhost:1221/motos?city=tunja

### por color
GET http://localhost:1221/motos?color=orange

### creamos una moto con POST
POST http://localhost:1221/motos
Content-Type: application/json

{
  "img": "https://raw.githubusercontent.com/pac13/motos-img/master/mt-03.png",
  "model": "Mt 03",
  "description": "Description about motorcycle...",
  "city": ["Bogotá"],
  "brand": ["Yamaha"],
  "price": 1900,
  "new": true,
  "year": 2012,
  "color": ["blue", "black"],
  "velMax": 180
}

###
PATCH  http://localhost:1221/motos/99f66521-773a-11ee-b1c2-900f0c2fe266
Content-Type: application/json

{
  "year": 2023
}

###
DELETE http://localhost:1221/motos/99f66521-773a-11ee-b1c2-900f0c2fe266
