### motos-api
GET http://localhost:1221/motos

### por id
GET http://localhost:1221/motos/2

### por marca
GET http://localhost:1221/motos?brand=ktm

### por ciudad
GET http://localhost:1221/motos?city=cúcuta

### por color
GET http://localhost:1221/motos?color=orange

### creamos una moto con POST
POST http://localhost:1221/motos
Content-Type: application/json

{
  "img": "https://raw.githubusercontent.com/pac13/motos-img/master/ninja-300.png",
  "model": "Ninja 300",
  "description": "Description about motorcycle...",
  "city": ["Bogotá"],
  "brand": ["Kawasaki"],
  "price": 1500,
  "new": true,
  "year": 2021,
  "color": ["green", "black", "gray"],
  "velMax": 180
}

###
PATCH  http://localhost:1221/motos/1
Content-Type: application/json

{
  "year": 2024
}

###
DELETE http://localhost:1221/motos/e4e44be1-4b13-4614-88cb-418b64761c0b
